server:
  port: 9090

spring:
  redis:
    host: ubuntu.wsl
    port: 6379
    password: 123456
    database: 0
    connect-timeout: 1000
    lettuce:
      pool:
        enabled: true
        max-active: 10
        max-idle: 10
        min-idle: 10
        max-wait: 1000ms