server:
  port: 8080
spring:
  application:
    name: dubbo-client-app
dubbo:
  application:
    name: ${spring.application.name}
    qos-port: 20030
  registries:
    # 多注册中心
    nacos:
      register: true
      address: nacos://127.0.0.1:8848
      weight: 10

