server:
  port: 9090
  tomcat:
    threads:
      max: 1000
    connection-timeout: 20000
    accept-count: 1000

spring:
  # =============DataSource=============
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&userSSL=false
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      pool-name: test-datasource
      connection-timeout: 10000
  redis:
    host: 172.28.152.185
    port: 6379
    database: 0
    connect-timeout: 1000
    lettuce:
      pool:
        enabled: true
        max-active: 10
        max-idle: 10
        min-idle: 10
        max-wait: 1000ms
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # sql语句打印