spring:
  application:
    name: dubbo-server-app
dubbo:
  application:
    name: ${spring.application.name}
  registries:
    # 多注册中心
    nacos:
      register: true
      address: nacos://127.0.0.1:8848
      weight: 10
  protocol:
    name: dubbo
    port: -1

